version: '2'
services:
  mysql:
    image: dockerized-image-mysql
    volumes:
      - dockerizeddata:/var/lib/mysql
    restart: 'always'
    expose:
    - '3307'
    ports:
    - '3307:3306'
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - dockerized

  php:
    depends_on:
      - mysql
    user: root
    links:
      - mysql
    image: dockerized-image-php
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
    volumes:
      - .:/var/www/html
      - ./dockers/php/php.ini:/usr/local/etc/php/php.ini
    env_file: .env
    working_dir: /var/www/html
    networks:
      - dockerized

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306
    networks:
      - dockerized

volumes:
    dockerizeddata:
      driver: local

networks:
  dockerized:
    driver: bridge
